version: '3'
services:
  service-manager:
    image: mf2c/service-manager:1.4
    environment:
      - JAVA_OPTS=
      - CIMI_URL=https://dashboard.mf2c-project.eu/api
    expose:
      - 46200
#  slalite:
#    image: mf2c/sla-management:0.2.2
#    environment:
#      - SLA_CIMIURL=https://dashboard.mf2c-project.eu/api
#    expose:
#      - 8090